name: shader_buffers_fork
description: >-
  Using shaders to feed a shader. Make shaders simplier
  to use with a focus on the ShaderToy.com website.

  A fork of shader_buffers_fork.
version: 0.0.1
homepage: https://github.com/thomashandlag/shader_buffers_fork
issue_tracker: https://github.com/thomashandlag/shader_buffers_fork/issues
repository: https://github.com/thomashandlag/shader_buffers_fork
topics:
  - shader
  - shadertoy

environment:
  sdk: ^3.11.1
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  
  flutter_test:
    sdk: flutter

flutter:

  assets:
    - assets/
